import './Grid.css';
import Square from './Square';

export default function Grid({playerId, squares, step, indexToPlace, setIndexToPlace, indexToBuild, setIndexToBuild, indexesToBuild, setIndexesToBuild}) {

    return <div className="grid">
        <div className="column">
            <Square 
                index={0} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={4} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={8} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={12} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
        </div>
        <div className="column">
        <Square 
                index={1} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={5} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>            
            <Square 
                index={9} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={13} 
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
        </div>
        <div className="column">
            <Square 
                index={2}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>            
            <Square 
                index={6}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={10} step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={14}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>    
        </div>
        <div className="column">
        <div className="column">
            <Square 
                index={3}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>            
            <Square 
                index={7}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={11} step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>
            <Square 
                index={15}
                step={step} 
                indexToPlace={indexToPlace} 
                setIndexToPlace={setIndexToPlace} 
                indexToBuild={indexToBuild} 
                setIndexToBuild={setIndexToBuild} 
                indexesToBuild={indexesToBuild} 
                setIndexesToBuild={setIndexesToBuild}
                squares={squares}
            ></Square>    
        </div>        </div>
    </div>;
}
